import 'nikon_monitor_values.dart';

const exifLabels = <String, String>{
  'Make': '相机品牌',
  'Model': '相机型号',
  'LensMake': '镜头品牌',
  'LensModel': '镜头型号',
  'LensSpecification': '镜头规格',
  'BodySerialNumber': '机身序列号',
  'LensSerialNumber': '镜头序列号',
  'ExposureTime': '曝光时间（秒）',
  'FNumber': '光圈值',
  'ApertureValue': '光圈（APEX）',
  'MaxApertureValue': '最大光圈（APEX）',
  'ShutterSpeedValue': '快门速度（APEX）',
  'PhotographicSensitivity': '感光度 ISO',
  'ISOSpeedRatings': '感光度 ISO',
  'SensitivityType': '感光度类型',
  'RecommendedExposureIndex': '推荐曝光指数',
  'StandardOutputSensitivity': '标准输出感光度',
  'ISOSpeed': 'ISO 速度',
  'FocalLength': '焦距（毫米）',
  'FocalLengthIn35mmFilm': '等效 35mm 焦距',
  'DateTimeOriginal': '拍摄时间',
  'DateTimeDigitized': '数字化时间',
  'DateTime': '修改时间',
  'OffsetTime': '时区',
  'OffsetTimeOriginal': '拍摄时区',
  'OffsetTimeDigitized': '数字化时区',
  'SubSecTime': '亚秒时间',
  'SubSecTimeOriginal': '拍摄亚秒',
  'SubSecTimeDigitized': '数字化亚秒',
  'ImageWidth': '图像宽度',
  'ImageLength': '图像高度',
  'PixelXDimension': '像素宽度',
  'PixelYDimension': '像素高度',
  'Orientation': '图像方向',
  'ExposureBiasValue': '曝光补偿（EV）',
  'ExposureProgram': '曝光程序',
  'ExposureMode': '曝光模式',
  'MeteringMode': '测光模式',
  'WhiteBalance': '白平衡',
  'LightSource': '光源',
  'Flash': '闪光灯',
  'ColorSpace': '色彩空间',
  'SceneCaptureType': '拍摄场景',
  'SceneType': '场景类型',
  'Contrast': '对比度',
  'Saturation': '饱和度',
  'Sharpness': '锐度',
  'BrightnessValue': '亮度（APEX）',
  'DigitalZoomRatio': '数码变焦倍率',
  'SubjectDistance': '主体距离（米）',
  'SubjectDistanceRange': '主体距离范围',
  'SubjectArea': '主体区域',
  'SubjectLocation': '主体位置',
  'SensingMethod': '传感器类型',
  'FileSource': '文件来源',
  'CustomRendered': '自定义处理',
  'GainControl': '增益控制',
  'Artist': '作者',
  'Copyright': '版权',
  'Software': '处理软件',
  'ImageDescription': '图片描述',
  'UserComment': '用户备注',
  'ImageUniqueID': '图像唯一标识',
  'CameraOwnerName': '相机所有者',
  'ExifVersion': 'EXIF 版本',
  'FlashpixVersion': 'FlashPix 版本',
  'Compression': '压缩方式',
  'CompressedBitsPerPixel': '每像素压缩位数',
  'BitsPerSample': '采样位深',
  'SamplesPerPixel': '像素采样数',
  'PhotometricInterpretation': '像素颜色解释',
  'XResolution': '水平分辨率',
  'YResolution': '垂直分辨率',
  'ResolutionUnit': '分辨率单位',
  'FocalPlaneXResolution': '焦平面水平分辨率',
  'FocalPlaneYResolution': '焦平面垂直分辨率',
  'FocalPlaneResolutionUnit': '焦平面分辨率单位',
  'YCbCrPositioning': '色度定位',
  'GPSLatitude': 'GPS 纬度',
  'GPSLatitudeRef': '纬度方向',
  'GPSLongitude': 'GPS 经度',
  'GPSLongitudeRef': '经度方向',
  'GPSAltitude': '海拔（米）',
  'GPSAltitudeRef': '海拔基准',
  'GPSDateStamp': 'GPS 日期',
  'GPSTimeStamp': 'GPS 时间',
  'GPSImgDirection': '拍摄方向',
  'GPSImgDirectionRef': '方向基准',
  'GPSSpeed': '移动速度',
  'GPSSpeedRef': '速度单位',
  'GPSProcessingMethod': 'GPS 定位方式',
  'GPSMapDatum': 'GPS 大地基准',
  'GPSStatus': 'GPS 状态',
  'GPSMeasureMode': 'GPS 测量模式',
  'GPSDOP': 'GPS 精度',
  'GPSSatellites': 'GPS 卫星',
  'GPSVersionID': 'GPS 版本',
  'GPSTrack': '运动方向',
  'GPSTrackRef': '运动方向基准',
  'DNGVersion': 'DNG 版本',
  'DefaultCropSize': '默认裁切尺寸',
  'NewSubfileType': '子文件类型',
  'ThumbnailImageWidth': '缩略图宽度',
  'ThumbnailImageLength': '缩略图高度',
};

String exifValue(String key, String value) {
  final parts = value.split('/');
  final n = parts.length == 2
      ? (double.tryParse(parts[0]) ?? 0) / (double.tryParse(parts[1]) ?? 1)
      : double.tryParse(value);
  if (n != null && n.isFinite && n > 0) {
    if (key == 'ExposureTime') return shutterLabel(n);
    if (key == 'FNumber') {
      return 'f/${exposureNumber(nominalExposure(n, thirdStopAperture))}';
    }
    if (key == 'PhotographicSensitivity' || key == 'ISOSpeedRatings') {
      return isoLabel(n.round());
    }
  }
  const values = <String, Map<String, String>>{
    'ExposureProgram': {
      '0': '未定义',
      '1': '手动 M',
      '2': '程序自动 P',
      '3': '光圈优先 A',
      '4': '快门优先 S',
      '5': '创意程序',
      '6': '运动程序',
      '7': '人像',
      '8': '风景',
    },
    'ExposureMode': {'0': '自动曝光', '1': '手动曝光', '2': '自动包围曝光'},
    'WhiteBalance': {'0': '自动白平衡', '1': '手动白平衡'},
    'MeteringMode': {
      '0': '未知',
      '1': '平均测光',
      '2': '中央重点',
      '3': '点测光',
      '4': '多点测光',
      '5': '矩阵 / 分区测光',
      '6': '局部测光',
      '255': '其他',
    },
    'LightSource': {
      '0': '未知',
      '1': '日光',
      '2': '荧光灯',
      '3': '白炽灯',
      '4': '闪光灯',
      '9': '晴天',
      '10': '阴天',
      '11': '阴影',
      '12': '日光荧光灯',
      '13': '昼白色荧光灯',
      '14': '冷白色荧光灯',
      '15': '白色荧光灯',
      '17': '标准光源 A',
      '18': '标准光源 B',
      '19': '标准光源 C',
      '20': 'D55',
      '21': 'D65',
      '22': 'D75',
      '23': 'D50',
      '24': 'ISO 摄影棚钨丝灯',
      '255': '其他',
    },
    'ColorSpace': {'1': 'sRGB', '2': 'Adobe RGB', '65535': '未校准 / 自定义'},
    'Orientation': {
      '1': '正常',
      '2': '水平镜像',
      '3': '旋转 180°',
      '4': '垂直镜像',
      '5': '转置',
      '6': '顺时针 90°',
      '7': '横向转置',
      '8': '逆时针 90°',
    },
    'SceneCaptureType': {'0': '标准', '1': '风景', '2': '人像', '3': '夜景'},
    'Contrast': {'0': '标准', '1': '柔和', '2': '强烈'},
    'Saturation': {'0': '标准', '1': '低饱和度', '2': '高饱和度'},
    'Sharpness': {'0': '标准', '1': '柔和', '2': '锐利'},
    'CustomRendered': {'0': '标准处理', '1': '自定义处理'},
    'SubjectDistanceRange': {'0': '未知', '1': '微距', '2': '近景', '3': '远景'},
    'ResolutionUnit': {'1': '无单位', '2': '英寸', '3': '厘米'},
    'GPSLatitudeRef': {'N': '北纬', 'S': '南纬'},
    'GPSLongitudeRef': {'E': '东经', 'W': '西经'},
    'GPSAltitudeRef': {'0': '海平面以上', '1': '海平面以下'},
    'GPSSpeedRef': {'K': '千米 / 小时', 'M': '英里 / 小时', 'N': '节'},
  };
  final translated = values[key]?[value];
  if (translated != null) return '$translated（$value）';
  if (key == 'Flash') {
    final n = int.tryParse(value);
    if (n != null) {
      return '${n & 1 != 0 ? "已闪光" : "未闪光"}${n & 64 != 0 ? " · 防红眼" : ""}（$value）';
    }
  }
  return value;
}
