#!/usr/bin/env python3
"""Record hashes and reproducible sources for custom release assets."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def entry(path: Path, generator: str, role: str) -> dict[str, str]:
    return {
        "path": path.relative_to(ROOT).as_posix(),
        "sha256": digest(path),
        "source": generator,
        "role": role,
    }


def generate() -> None:
    resources: list[dict[str, str]] = []
    for path in [ROOT / "assets/demo.png", ROOT / "assets/demo_raw.png"]:
        resources.append(entry(path, "Project photograph", "demonstration photograph"))
    for path in sorted((ROOT / "assets/watermark_templates").glob("*.png")):
        resources.append(entry(path, "Generated by scripts/generate_visual_assets.py", "generated watermark preview"))
    for path in sorted((ROOT / "android/app/src/main/assets/luts").glob("*.cube")):
        resources.append(entry(path, "Generated by scripts/generate_luts.py", "generated 3D Cube preset"))
    for name in ["live_view.vert", "live_view.frag"]:
        path = ROOT / "android/app/src/main/assets" / name
        resources.append(entry(path, "MirrorBridge source", "GLES live-view shader"))
    for path in sorted((ROOT / "android/app/src/main/res").glob("mipmap-*/ic_launcher.png")):
        resources.append(entry(path, "Project launcher artwork", "launcher icon"))
    for path in sorted((ROOT / "assets/brand").glob("*.png")) + sorted((ROOT / "assets/demo_media").glob("*.png")) + sorted((ROOT / "assets/editor_presets").glob("*.png")) + [
        ROOT / "android/app/src/main/res/drawable/ic_launcher_foreground.png",
        ROOT / "android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml",
    ]:
        resources.append(entry(path, "Project demo artwork", "brand or demonstration asset"))
    manifest = {
        "schemaVersion": 1,
        "generatedBy": "scripts/generate_source_manifest.py",
        "resources": resources,
    }
    (ROOT / "assets/SOURCE_MANIFEST.json").write_bytes(
        (json.dumps(manifest, indent=2, ensure_ascii=True) + "\n").encode("ascii")
    )


if __name__ == "__main__":
    generate()
