#!/usr/bin/env python3
"""Generate MirrorBridge's built-in 3D Cube presets deterministically."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "android/app/src/main/assets/luts"
SIZE = 17

PRESETS = {
    "Warm Tone": dict(temperature=0.055, saturation=1.04, contrast=1.03, lift=0.005),
    "Cool Tone": dict(temperature=-0.050, saturation=1.02, contrast=1.02, lift=0.005),
    "Vivid Color": dict(temperature=0.000, saturation=1.24, contrast=1.12, lift=0.000),
    "Soft Light": dict(temperature=0.012, saturation=0.92, contrast=0.88, lift=0.045),
    "Matte Film": dict(temperature=0.018, saturation=0.88, contrast=0.92, lift=0.075),
    "Monochrome": dict(temperature=0.000, saturation=0.00, contrast=1.08, lift=0.010),
    "High Contrast": dict(temperature=0.000, saturation=1.05, contrast=1.28, lift=-0.015),
    "Sepia Print": dict(temperature=0.025, saturation=0.18, contrast=1.06, lift=0.020, sepia=0.72),
}


def clamp(value: float) -> float:
    return max(0.0, min(1.0, value))


def transform(red: float, green: float, blue: float, parameters: dict[str, float]) -> tuple[float, float, float]:
    luma = red * 0.2126 + green * 0.7152 + blue * 0.0722
    saturation = parameters["saturation"]
    channels = [luma + (value - luma) * saturation for value in (red, green, blue)]
    contrast = parameters["contrast"]
    lift = parameters["lift"]
    channels = [(value - 0.5) * contrast + 0.5 + lift for value in channels]
    temperature = parameters["temperature"]
    channels[0] += temperature
    channels[1] += temperature * 0.12
    channels[2] -= temperature
    sepia = parameters.get("sepia", 0.0)
    if sepia:
        gray = sum(channels) / 3.0
        sepia_rgb = (gray * 1.08, gray * 0.94, gray * 0.72)
        channels = [value + (tone - value) * sepia for value, tone in zip(channels, sepia_rgb)]
    return tuple(clamp(value) for value in channels)


def generate() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for old in OUTPUT.glob("*.cube"):
        old.unlink()
    for name, parameters in PRESETS.items():
        lines = [
            f'TITLE "MirrorBridge {name}"',
            f"# Generated by scripts/generate_luts.py with {json.dumps(parameters, sort_keys=True)}",
            f"LUT_3D_SIZE {SIZE}",
            "DOMAIN_MIN 0.0 0.0 0.0",
            "DOMAIN_MAX 1.0 1.0 1.0",
        ]
        for blue_index in range(SIZE):
            for green_index in range(SIZE):
                for red_index in range(SIZE):
                    values = transform(
                        red_index / (SIZE - 1),
                        green_index / (SIZE - 1),
                        blue_index / (SIZE - 1),
                        parameters,
                    )
                    lines.append(" ".join(f"{value:.7f}" for value in values))
        filename = name.replace(" ", "%20") + ".cube"
        (OUTPUT / filename).write_bytes(("\n".join(lines) + "\n").encode("ascii"))
    (ROOT / "assets/luts.json").write_bytes(
        (json.dumps(list(PRESETS), ensure_ascii=True, indent=2) + "\n").encode("ascii")
    )


if __name__ == "__main__":
    generate()
